### ISSUE TITLE
prices and revenues are offline/broken

### ISSUE THREAD

**Issue by ezi0o** [danclough/reaction-toolkit#9]
hey there, amazing website and service but sadly there seems to be a bug because all "costs" column for each reaction is empty "0" and the net incom of each reaction shows "-30,000,000.00 ISK".
Is there any way to fix this, as it makes the website useless :(
maybe its due to the fact that its not using the new ESI api ?
thanks for looking into it, such an amazing website @drclough

**Comment by danclough** [comment]
Thanks for bringing this to my attention.  It appears EVE-Central went down some time ago.  All of their API endpoints are still accessible, but return the default nginx starter page.  I just switched the live site to use EVE-MarketData instead and it's updating correctly.

**Comment by ezi0o** [comment]
Thx a lot mate

**Comment by ezi0o** [comment]
The "
Historical Trend over Last 30 days" of any item is still broken mate

**Comment by danclough** [comment]
Yeah, daily prices are saved to the historical price table at midnight every night.  No market data for that day = no historical data saved to the table, so nothing's been saved to the history since EVE-Central went down.  It'll start saving new historical prices today.  Everything between then and now will still read 0.

**Comment by ezi0o** [comment]
Thx! Such an amazing tool !

Three questions:

- Do you have any plans to adapt the "setup config" they uses a POS setup
to using the new refineries ?

- what do you think about removing the the last "cents" digits to every
price as it makes real long numbers and are such little detail when you
work with billions (i.e.: tel Je the ",00" from "Hexite 419,728,920.00
ISK")?

- have the possibility to remove from setup config the GSF tax and also the
shipping costs as they can be done solo if not done inside GSF space ? (Aka
just having the option to make the calculation more "generic" for those
doing réactions outside GSF space)

Thanks a lot
